### ISSUE TITLE
这个怎么用？

### ISSUE THREAD

**Issue by easydowork** [treemonster/chrome-dev-tool#1]

**Comment by treemonster** [comment]
1. 安装依赖包 `npm install`
2. 运行 `node .`
3. 访问网页时本程序会把加载到的Script和Document类型的文件会写入到data下
4. 修改对应的文件，然后刷新页面看效果

**Comment by easydowork** [comment]
```sh
module.js:491                                                                        
throw err;                                                                       
^                                                                                                                                                             
Error: Cannot find module 'js-base64'                                                
at Function.Module._resolveFilename (module.js:489:15)                           
at Function.Module._load (module.js:439:25)                                      
at Module.require (module.js:517:17)                                             
at require (internal/module.js:11:18)                                            
at Object. (D:\chrome-dev-tool\index.js:3:16)                         
at Module._compile (module.js:573:30)                                            
at Object.Module._extensions..js (module.js:584:10)                              
at Module.load (module.js:507:32)                                                
at tryModuleLoad (module.js:470:12)                                             
 at Function.Module._load (module.js:462:3)
--
```

windows 下 安装不了这个模块

**Comment by treemonster** [comment]
我忘了在package.json里加上js-base64这个包了，不好意思。现在已经加上了，你再安装一次试试？

**Comment by ZhangKejun** [comment]
localhost:chrome-dev-tool-master zhangkejun$ node .
/Users/zhangkejun/Downloads/chrome-dev-tool-master/core/index.js:6
const newBrowser=(headless, hooks_js_inject, defaultUrl)=>watchClient(async (client, page)=>{
                                                                            ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zhangkejun/Downloads/chrome-dev-tool-master/bin/index.js:1:74)

你好，MAC运行，这又是什么错误呢？

**Comment by treemonster** [comment]
@ZhangKejun 可能是node版本过低了，使用10.0以上的node试一下吧

**Comment by ZhangKejun** [comment]
> @ZhangKejun 可能是node版本过低了，使用10.0以上的node试一下吧

升级后可以了，谢谢；

还想请教个问题，你使用过微信小程序开发工具吗，知道他们的那个真机远程调试是怎么弄的吗？是基于谷歌的这个远程调试协议吗？
